app_forum/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add/$', add, name='add'),
	url(r'^delete/(?P<id>\d)/$', delete_forum, name='delete_forum'),
]

app_home/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index, unfinished

urlpatterns = [
    url(r'^profile/$', index, name='index'),
    url(r'^under-construction/$', unfinished, name='under-construction'),
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_home.urls as app_home
import app_profile.urls as app_profile
import app_forum.urls as app_forum

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(app_home,namespace='app_home')),
    url(r'^company/forum/', include(app_forum,namespace='app_forum')),
    url(r'^company/', include(app_profile,namespace='app_profile')),
    url(r'^$',RedirectView.as_view(url='home/',permanent=True),name='index'),
]

app_forum/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=500)
    company_id = models.IntegerField(default=0)

app_home/models.py
from django.db import models

# Create your models here.

app_profile/models.py
from django.db import models

# Create your models here.

app_forum/forms.py
from django import forms

class ForumForm(forms.Form):
	content_attrs = {
		'class': 'form-control',
		'placeholder': 'Insert Description'
	}
	content = forms.CharField(max_length=500, widget=forms.TextInput(attrs=content_attrs))

app_forum/views.py
from django.shortcuts import render, redirect
from .models import Forum
from .forms import ForumForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}
def index(request):
    forum_list = Forum.objects.all()
    paginator = Paginator(forum_list, 3)

    page = request.GET.get('page')
    try:
        forum = paginator.page(page)
    except:
        forum = paginator.page(1)

    response['forum'] = forum
    return render(request, 'app_forum/forum.html', response)

def add(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        response['form'] = form
        if form.is_valid():
            Forum.objects.create(content=form.cleaned_data['content'])
            forum = Forum.objects.all()
            response['forum'] = forum
            return redirect('company/forum/')
        else:
            forum = Forum.objects.all()
            response['forum'] = forum
            response['form'] = form
#            return render(request, 'test.html', response)
    return redirect('company/forum/')

def delete_forum(request, id):
    to_delete = Forum.objects.get(id=id)
    to_delete.delete()
    return redirect('company/forum/')

app_home/views.py
from django.shortcuts import render

response = {}
def index(request):
	html = 'app_home/app_home.html'
	return render(request, html, response)

app_profile/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

response = {}
def index(request):
	html = 'app_profile/app_profile.html'
	return render(request, html, response)

def unfinished(request):
	html = 'app_profile/almost-there.html'
	return render(request, html, response)

app_forum/templates/app_forum/forum.html
{% extends "app_forum/layout/base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}


<script type="text/javascript" src="//platform.linkedin.com/in.js">
  api_key:   86566ytexriwrs
  onLoad:    checkLoggedIn
  authorize: true
</script>

  <section style="display: none;">
    <!-- Main body -->
    <div class="container" style="margin-top: 60px; padding-top: 15px;">
      <div class="row">
        <h3>Forum Lowongan</h3>
      </div>
      <button type="button" class="btn btn-danger" onclick="logout()">logout</button>
      <div class="row">
        <div class="col-sm-12">
          <div class="flex" style="margin-top: 20px">
            <div class="card-block">
              <!-- Form for new status -->
              <form class="card-text" method="POST" action="{% url 'app_forum:add' %}">
                {% csrf_token %}
                <div class="card">
                  <div class="card-header" style="font-family: Spectral SC">
                    Deskripsi
                  </div>
                    <textarea class="form-control" name="content" rows="5" id="content" style="width: 100%" title="content"></textarea>
            
                </div>
              <button type="submit" class="btn btn-primary float-left" style="margin: 10px 0 25px 0" id="button"> Submit </button>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <!-- Print errors if any -->
    {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
    {% for i in forum reversed %}
      <div class="card">
        <div class="card-header" style="font-family: Spectral SC" id="lowongan">
          Lowongan
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p class="card-text"> {{ i.content }} </p>
            <footer class="blockquote-footer">{{ i.date }}</footer>
          </blockquote>
        </div>
      </div>
    {% endfor %}
    </div>

        <nav>
          {% if forum.has_other_pages %}
          <ul class="pagination" style="justify-content: center; margin-top: 20px">
            {% if forum.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ forum.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in forum.paginator.page_range %}
              {% if forum.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if forum.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ forum.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
    </section>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}

app_forum/templates/app_forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="{{nama_perusahaan}}">
   <!-- bootstrap csss -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script src="{% static 'js/forum.js' %}"></script>

   <title>
       {% block title %} {{nama_perusahaan}} {% endblock %}
   </title>
</head>
<body style = "background-color :  #d6eaf8 ">
   <header style = "position : fixed; top  : 0">
       {% include "app_forum/partials/header.html" %}
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   {% block javascript %}
   {% endblock %}
</body>
<footer  style = "position : static; margin-bottom : 0; width : 100%">
       {% block footer %}
       {% include "app_forum/partials/footer.html" %}
       {% endblock %}
   </footer>
</html>

app_forum/templates/app_forum/partials/footer.html
<!-- templates/app_forum/partials/footer.html -->
<div class="panel-footer footer">
  <p id='footer' style="color: black">Made with Love by &copy; PPW-E -> Kelompok-6</p>
</div>

app_forum/templates/app_forum/partials/header.html
<!-- templates/app_forum/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'app_home:index' %}">Home</a>
      <a class="navbar-brand" href="{% url 'app_profile:index' %}">Profile</a>
      <a class="navbar-brand" href="{% url 'app_forum:index' %}">Forum</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    </div>
  </div>
</nav>

app_home/templates/app_home/app_home.html
{% extends "app_home/layout/base.html" %}
{% block content %}
<head>

	<script>
	    // Setup an event listener to make an API call once auth is complete
	    function onLinkedInLoad() {
	    	console.log("Masuk onLinkedInLoad")
	        IN.Event.on(IN, "auth", getProfileData);
	    }

	    // Handle the successful return from the API call
	    function onSuccess(data) {
	        console.log(data);
	    }

	    // Handle an error response from the API call
	    function onError(error) {
	        console.log(error);
	    }

	    // Use the API call wrapper to request the member's basic profile data
	    function getProfileData() {
	        window.location.replace("/company/profile");
	    }


	</script>
	<script type="text/javascript" src="//platform.linkedin.com/in.js">
	    api_key:   86566ytexriwrs
	    authorize: true
	    onLoad : onLinkedInLoad
	</script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
</head>

<br/>
<br/>
<br/>
<div style = " display: flex; flex-direction: column; height :100%; flex-basis : 0" id = "app_home">
	<div style = "margin-left : 10% ; margin-bottom : 15px;margin-right : 20%; display : flex" id = "welcome-text">
		<div>
			<img class = "center-block" src = "https://www.cultavo.com/assets/landing/company_icon_blue-544f6e86d8d7132fa66216a587c799ba2e66846567f3e5d702a8d11d095788a8.png" height = 220 width = 220 >
		</div>
		<div>
			<h1 style = "color : #0077B5 ; font-size : 25px"> Buka Hati</h1>
			<p> We're Hiring! </p>
			<br/>
			<p> Our availabe position : </p>
			<p>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  1. Web Developer </p>
			<p>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  2. Mobile Developer </p>
		</div>
	</div>
	<div style = "margin-left : 30%;">
		<!-- ada yang komentar -->
		<div style = "margin-bottom : 30px; display : flex">
			<div>
				<img src = "https://cdn4.iconfinder.com/data/icons/round-buttons/512/blue_user.png" height = 100 width = 100>
			</div>
			<div style = "margin-left : 25px">
				<h1 style = "color : #0077B5 ; font-size : 15px"> Bintang </h1>
				<p style = "font-size : 12px"> Pak itu digaji nggak </p>
			</div>
		</div>
		<!-- reply nya -->
		
		<div style = "margin-bottom : 30px; display : flex">
			<div>
				<img src = "https://www.cultavo.com/assets/landing/company_icon_blue-544f6e86d8d7132fa66216a587c799ba2e66846567f3e5d702a8d11d095788a8.png" height = 115 width = 115 >
			</div>
			<div style = "margin-left : 25px">
				<h1 style = "color : #0077B5 ; font-size : 15px"> Buka Hati </h1>
				<p style = "font-size : 12px"> Sure it is. The salary is fantastic here! </p>
			</div>
		</div>
	</div>
	<div style = "display: flex; width : 100%; flex-basis : 0" id='button'>
		<div style = "margin-left : 12%">
			<button style = "background-color: #0077B5; border: none; color: white; padding: 1px 10px;text-align: center;text-decoration: display: inline-block;font-size: 12px;" id = "mhlogin">Login Mahasiswa</button>
    	</div>
    	<div style = "margin-left : 60%">
			<script type="in/Login"></script>
		</div>
	</div>
</div>

{% endblock %}

app_home/templates/app_home/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="{{nama_perusahaan}}">
   <!-- bootstrap csss -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/app_home.css' %}" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script src="{% static 'js/app_home.js' %}"></script>

   <title>
       {% block title %} {{nama_perusahaan}} {% endblock %}
   </title>
</head>
<body style = "background-color :  #d6eaf8 ">
   <header style = "position : fixed; top  : 0">
       {% include "app_home/partials/header.html" %}
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   {% block javascript %}
   {% endblock %}
</body>
<footer  style = "position : static; margin-bottom : 0; width : 100%">
       {% block footer %}
       {% include "app_home/partials/footer.html" %}
       {% endblock %}
   </footer>
</html>

app_home/templates/app_home/partials/footer.html
<p style = "margin-bottom : 0; text-align:center; width:100%; color: black" class="panel-footer footer" id='footer'>Made with Love by &copy; PPW-E -> Kelompok-6</p>

app_home/templates/app_home/partials/header.html
<!-- templates/app_home/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'app_home:index' %}">Home</a>
      <a class="navbar-brand" href="{% url 'app_profile:index' %}">Profile</a>
      <a class="navbar-brand" href="{% url 'app_forum:index' %}">Forum</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    </div>
  </div>
</nav>

app_profile/templates/app_profile/almost-there.html
<!DOCTYPE>
<html>
  <head>
    <title>Under Construction</title>
  </head>
  <body style="text-align: center;">
  	{% load static %}
    <img src="{% static "img/under-construct.jpg" %}" id="image">
    <div id="copyright-claim" style="font-size: 12px" onclick="location.href='http://www.itf.gov.ng/img/UnderConstruct.jpg'">Image is the copyright of {http://www.itf.gov.ng/img/UnderConstruct.jpg}</div>
    <button id="back-button" onclick="goback()">I want to go back</button>
  </body>

  <script type="text/javascript">
  function goback() {
    window.location.replace("/company/profile");
  }
  </script>
</html>

app_profile/templates/app_profile/app_profile.html
{% extends "app_profile/layout/base.html" %}
{% block content %}

<head>
  <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   86566ytexriwrs
    authorize: true
    onLoad : onLinkedInLoad
  </script>
</head>

<button class="pull-right" id="logout-button" onclick="logout()">logout</button>
<img class="pull-right" id="corp-small-image"></img>
<h3 id="welcome-message"></h3>

{% load static %}
<img src="{% static "img/buildings.png" %}" id="corp-main-image"></img>
<hr>
<button class="center-block" id="forum-list-button" onclick="toForum()">Lihat Forum</button>
<button class="center-block" id="mahasiswa-list-button" onclick="underconst()">Cari Mahasiswa</button>

<table cellspacing="15px">
  <tr>
    <td>Tipe Perusahaan</td>
    <td class="isi" id="tipe"></td>
  </tr>
  <tr>
    <td>Web Perusahaan</td>
    <td class="isi" id="web"></td>
  </tr>
  <tr>
    <td>Spesialitas</td>
    <td class="isi" id="spesialitas"></td>
  </tr>

</table>
{% endblock %}

app_profile/templates/app_profile/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Ling In">
    <meta name="author" content="Kelompok 6">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_profile.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/app_profile.js' %}"></script>
    <title>
    {% block title %} Profile {{nama_perusahaan}} {% endblock %}
  </title>
</head>
<body>
  <header>
    {% include "app_profile/partials/header.html" %}
  </header>
  <content>
    {% block content %}
      <!-- content goes here -->
    {% endblock %}
  </content>
  {% block javascript %}
  {% endblock %}
</body>
<footer>
  {% block footer %}
  {% include "app_profile/partials/footer.html" %}
  {% endblock %}
</footer>
</html>

app_profile/templates/app_profile/partials/footer.html
<p style = "margin-bottom : 0; text-align:center; width:100%; color: black" class="panel-footer footer" id='footer'>Made with Love by &copy; PPW-E -> Kelompok-6</p>

app_profile/templates/app_profile/partials/header.html
<!-- templates/app_profile/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'app_home:index' %}">Home</a>
      <a class="navbar-brand" href="{% url 'app_profile:index' %}">Profile</a>
      <a class="navbar-brand" href="{% url 'app_forum:index' %}">Forum</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    </div>
  </div>
</nav>